spring:
  application:
    name: project1
  #view settings
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  #mybatis map snake case to camel case
  datasource:
    url: jdbc:mariadb://192.168.35.14:3306/prj1
    username: root
    password: 1234
  #server session timeout
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: qECPn87eKQj2jORgYmsj
            client-secret: 66hn8P5D0t
            scope:
              - email
              - nickname
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌


server:
  servlet:
    session:
      timeout: 30m
  # db connection
mybatis:
  configuration:
    map-underscore-to-camel-case: true
## show sql log
#logging.level.com.project1.mapper=debug
